### ISSUE TITLE
libbytesize.so.1 does not link to PCRE2

### ISSUE THREAD

**Issue by mhmdanas** [storaged-project/libbytesize#129]
Trying to run bscalc on Void Linux (which packages libbytesize 2.7, though I can reproduce the issue when I bump the package to 2.8 locally), I get this error:
```
Traceback (most recent call last):
  File "/bin/bscalc", line 6, in <module>
    from bytesize import Size, ZeroDivisionError
  File "/usr/lib/python3.11/site-packages/bytesize/__init__.py", line 1, in <module>
    from .bytesize import Size
  File "/usr/lib/python3.11/site-packages/bytesize/bytesize.py", line 23, in <module>
    c_bytesize = ctypes.CDLL("libbytesize.so.1")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/ctypes/__init__.py", line 376, in __init__
    self._handle = _dlopen(self._name, mode)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^
OSError: /usr/lib/libbytesize.so.1: undefined symbol: pcre2_substring_get_byname_8
```
Here's the output of `ldd /usr/lib/libbytesize.so.1`:
```
        linux-vdso.so.1 (0x00007ffe39931000)
        libmpfr.so.6 => /usr/lib/libmpfr.so.6 (0x00007f27d3ded000)
        libgmp.so.10 => /usr/lib/libgmp.so.10 (0x00007f27d3d70000)
        libc.so.6 => /usr/lib/libc.so.6 (0x00007f27d3b87000)
        /usr/lib64/ld-linux-x86-64.so.2 (0x00007f27d3ebb000)
```

So for some reason, `libbytesize.so.1` is not linking to `libpcre2-8.so.0`. I asked on the Void Linux support channels about this, and was told that I should report this issue to libbytesize. Any idea how to fix this?

**Comment by tbzatek** [comment]
Hmm, output from Gentoo `dev-libs/libbytesize-2.8`:

```
# lddtree /usr/lib64/libbytesize.so.1
/usr/lib64/libbytesize.so.1 (interpreter => None)
    libmpfr.so.6 => /usr/lib64/libmpfr.so.6
        ld-linux-x86-64.so.2 => /lib64/ld-linux-x86-64.so.2
    libpcre2-8.so.0 => /lib64/libpcre2-8.so.0
    libgmp.so.10 => /usr/lib64/libgmp.so.10
    libc.so.6 => /lib64/libc.so.6
```

Output from Fedora 38 nightly `libbytesize-2.8-21.20230520043322360967.master.5.g8ff375c.fc38.x86_64`:

```
# ldd /usr/lib64/libbytesize.so.1
	linux-vdso.so.1 (0x00007ffd36d73000)
	libmpfr.so.6 => /lib64/libmpfr.so.6 (0x00007fb674729000)
	libpcre2-8.so.0 => /lib64/libpcre2-8.so.0 (0x00007fb67468f000)
	libgmp.so.10 => /lib64/libgmp.so.10 (0x00007fb6745ea000)
	libc.so.6 => /lib64/libc.so.6 (0x00007fb67440c000)
	/lib64/ld-linux-x86-64.so.2 (0x00007fb6747f3000)
```

**Comment by ahesford** [comment]
This is the result of a misconfiguration of the Void Linux package.

**Comment by tbzatek** [comment]
So the problem is that most of the check are "soft" wrapped around `LIBBYTESIZE_SOFT_FAILURE` and such, only posting errors and a friendly warning at the end of the configure process:

```
*** Libbytesize encountered the following issues during configuration:
Package 'libpcre2-8', required by 'virtual:world', not found
Header file gmp.h not found.
Header file mpfr.h not found.

*** Libbytesize will not successfully build without these missing dependencies
```

This was a bad idea apparently as any such configure failure may go unnoticed in automated builds.
Any strong reason for not making it a fatal error? @vpodzime?

**Comment by vpodzime** [comment]
> This was a bad idea apparently as any such configure failure may go unnoticed in automated builds.
> Any strong reason for not making it a fatal error? @vpodzime?

I don't recall any reason why it's not a failure. IIRC, the goal of `SOFT_FAILURE` was to gather all the issues and show them in the end instead of failing on the first one. But it should still fail if there are some issues.

**Comment by tbzatek** [comment]
So `configure` actually exits with return code 1 but that's probably not always checked by distributors as the configured makefiles get created either way.
