### ISSUE TITLE
L10N Korean Team maintains the settings proposed through official translations.

### ISSUE THREAD

**Issue by simmon-nplob** [storaged-project/libbytesize#137]
L10N Korean Team maintains the settings proposed through official translations.
Please apply the changed translation.

_Originally posted by @simmon-nplob in https://github.com/storaged-project/blivet/discussions/1189#discussioncomment-8209605_

**Comment by vojtechtrefny** [comment]
I usually do not interfere in translations and I recognize your authority for the Korean translations, but the [latest change](https://github.com/storaged-project/libbytesize/pull/136) changed (or to be more precise *removed*) translations for 12 languages, which is something I am not going to accept from a single contributor.

**Comment by simmon-nplob** [comment]
I think so too. I made a suggestion and thought that it was necessary to consider this. We are participants, and we hope that these discussions and tests will yield better results. Have a wonderful day!
