### ISSUE TITLE
Size calculation does not work correctly on i686 due to integer type issues

### ISSUE THREAD

**Issue by AdamWill** [storaged-project/libbytesize#34]
Quoting from [this bugzilla comment](https://bugzilla.redhat.com/show_bug.cgi?id=1375732#c13) by Stefan Ring:

"The bug is in libbytesize's Python binding:

    >>> import bytesize.bytesize
    >>> bytesize.bytesize.Size(0) + 2**36
    Size (0 B)

Well, actually it's in the C part of libbytesize, because for example bs_size_add_bytes (responsible for the error shown above) takes a uint64_t, which it happily passes on to mpz_add_ui, which takes an unsigned long, and thus truncation happens.

A workaround would be replacing every occurrence of MAXUINT64 in bytesize.py with sys.maxsize. Of course, it would be better fixing the C interface, which would probably take a bit more work. Although, it would mostly consist of replacing uint64_t with unsigned long."

**Comment by vpodzime** [comment]
> takes a uint64_t, which it happily passes on to mpz_add_ui, which takes an unsigned long, and thus truncation happens.

I think the solution should be based on this particular wrong behavior. *libbytesize* needs to div-mod the ``uint64_t`` value and then use ``mpz_add_ui()`` multiple times to actually add the number. The same applies to other operations.
