### ISSUE TITLE
Where is the NEWS or Changelog file?

### ISSUE THREAD

**Issue by bdubbs** [storaged-project/libbytesize#39]
You upgraded for version 0.11 to 1.0.  What changed?  

Note that the git changelog is not really satisfactory.  It gives equal weight to a typo in a comment and major functionality changes.

Why not run 'make dist' before releasing a new tarball?

**Comment by bdubbs** [comment]
And why does the tarball named libbytesize-1.0.tar.gz expand to the directory libbytesize-libbytesize-1.0.  there is an extra libbytesize there.

**Comment by vpodzime** [comment]
I can see your points. Thanks for a heads-up!

**Comment by vpodzime** [comment]
> Why not run 'make dist' before releasing a new tarball?

We are using ``make release`` which ensures tags are created, translations are downloaded and ``distcheck`` is run.

**Comment by vpodzime** [comment]
I believe #40 covers all the other concerns. Feel free to reopen this issue if you still see any problem here.
