### ISSUE TITLE
Python 2 switch

### ISSUE THREAD

**Issue by luc14n0** [storaged-project/libbytesize#45]
Hi there! Would be to much work to create a switch to disable python 2 support?

**Comment by vpodzime** [comment]
No, I think it should be relatively easy. I'll try to look at it next week.

**Comment by luc14n0** [comment]
Thank you @vpodzime. The python-3-as-default movement already started among Linux distros.

**Comment by vpodzime** [comment]
@vojtechtrefny plans to work on this
