### ISSUE TITLE
Can `--privileged` option for `docker run` be removed for ppc64le

### ISSUE THREAD

**Issue by gururajrkatti** [storaged-project/libbytesize#84]
I am running the build and test as a part of the Ubuntu distribution for ppc64le.
This helps us simplify testing later when distributions are re-building and re-releasing.

During the build and test (DOCKER_FILE=".travis/Dockerfile.debian-testing"), I found that it makes use of `--privileged` for `docker run`. 

It fails for ppc64le since privileged containers are not supported for lxd backend. 
I also verified that without using this option, the travis build succeeds for ppc64le.

Wanted to check if it is okay to remove this option for ppc64le or is there any specific reason for including `--privileged` option.

**Comment by vojtechtrefny** [comment]
I think the privileged option shouldn't be needed, but Travis has a different opinion, see #85 But if it works for you, feel free to remove it.

**Comment by gururajrkatti** [comment]
Sure @vojtechtrefny, I will raise PR by removing it for ppc64le alone.

**Comment by vojtechtrefny** [comment]
Fixed in #87
